
spring:
    datasource:
        url: ${mealer.datasource.url:jdbc:postgresql://localhost:5432/mealer}
        username: ${mealer.datasource.username:postgres}
        password: ${mealer.datasource.password:postgres}
        driver-class-name: org.postgresql.Driver

mealer:
    jwt:
        secret: "aac16664e62c1912af12f091e31b8b46b53000c010196144a8f8898d82f4bf18"

