name: autodeploy

on:
    push:
        branches: ['main']

jobs:
    autodeploy:
        runs-on: ubuntu-latest
        env:
            FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
            REGISTRY: ghcr.io
            IMAGE_NAME: ${{ github.repository }}
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        steps:
            - uses: actions/checkout@v2

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v1
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Extract metadata (tags, labels) for Docker
              id: meta
              uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
              with:
                  images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

            - name: Setup Gradle
              uses: gradle/gradle-build-action@v2

            - name: Run build with Gradle Wrapper
              run: ./gradlew bootBuildImage

            - name: Install flyctl via https://github.com/superfly/flyctl-actions
              uses: superfly/flyctl-actions/setup-flyctl@master

            - name: Deploy to fly.io
              run: flyctl deploy --local-only --image ghcr.io/kris456/mealweek-frontend:main -t ${{ env.FLY_API_TOKEN }}