name: Build

on: [ push ]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:

            -   uses: actions/checkout@v3
            -   uses: ./.github/actions
                with:
                    token: ${{ secrets.GITHUB_TOKEN }}
            -   name: Test
                run: ./gradlew test

    buildAndPush:
        needs: [ test ]
        if: github.ref_name == 'master'
        runs-on: ubuntu-latest
        permissions:
            packages: write
        env:
            REGISTRY: ghcr.io
            something: "else"
            IMAGE_NAME: ${{ github.repository }}
        steps:
            -   uses: actions/checkout@v3
            -   uses: ./.github/actions
                with:
                    token: ${{ secrets.GITHUB_TOKEN }}

            -   name: Build native image
                run: ./gradlew bootBuildImage

            -   name: Set Image Tag Version
                run: echo "TAG_VERSION=$( ./gradlew properties -q | grep "^version:" | awk '{print $2}')" >> $GITHUB_ENV

            -   name: Tag Image
                run: docker tag ghcr.io/kris456/mealweek-backend:latest ghcr.io/kris456/mealweek-backend:${{ env.TAG_VERSION }}

            -   name: Login to Github Registry
                run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u USERNAME --password-stdin

            -   name: Push Image to DockerHub
                run: docker push ghcr.io/kris456/mealweek-backend:latest && docker push ghcr.io/kris456/mealweek-backend:${{ env.TAG_VERSION }}

    autodeploy:
        runs-on: ubuntu-latest
        if: github.ref_name == 'master'
        needs: [ test, buildAndPush ]
        permissions:
            packages: write
        env:
            FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        steps:
            -   uses: actions/checkout@v3
            -   uses: ./.github/actions
                with:
                    token: ${{ secrets.GITHUB_TOKEN }}

            -   name: Install flyctl via https://github.com/superfly/flyctl-actions
                uses: superfly/flyctl-actions/setup-flyctl@master

            -   name: Deploy to fly.io
                run: flyctl deploy --image ghcr.io/kris456/mealweek-backend:${{ env.TAG_VERSION }} -t ${{ env.FLY_API_TOKEN }}